spring.application.name=DeepFind Backend
server.address=127.0.0.1
server.port=8080
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
deepfind.storage.data-directory=${DEEPFIND_DATA_DIRECTORY:${user.home}/.deepfind}
